name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Toolchain Cache
      id: build-toolchain
      uses: actions/cache@v1
      with:
        path: tools/local
        key: build-toolchain
        
    - name: Build Toolchain
      if: steps.build-toolchain.outputs.cache-hit != 'true'
      run: |
        git submodule update --init
        ./build-tools 
        #ls -la
        
    - name: Build
      run: |
        bash ./marsh build

    - uses: actions/upload-artifact@master
      with:
         name: docs
         path: public/
